version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: npm test
workflows:
  version: 2
  lint:
    jobs:
      - lint
  test:
    jobs:
      - test
